### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Xghayor** [Kaiserabbas/leaderboard#2]
<h3>Good Job! implementing all the project requirements</h3>
<p>I would like to suggest that you use an API to post and get data, and consider removing local storage for better functionality.</p>

**Comment by ngalamac** [comment]
Hi @Kaiserabbas, you did a great job implementing this project. However, there are some minor issues I would like you to adjust;
- Firstly I will like you to use more specific and descriptive commit messages for your files. Some commit messages in your repository do not depict the files directed to.
For example, the commit message used for index.html [here](https://github.com/Kaiserabbas/leaderboard/tree/development/src) is describing a styling, not a markup
- I will also suggest you remove any header in your table of contents which you have not used in your document. For example, Live Demo and FAQ can be removed because you have not used it
